### ISSUE TITLE
Improve Markdown Styling

### ISSUE THREAD

**Issue by willow446** [equalitie/ouisync-web#12]
Right now the markdown rendering is reasonable, but heading sizing and spacing needs to be improved imo

**Comment by jnny** [comment]
Yes, related to #11 
Secondary header font size should be increased (##) - see FAQ page subheading (and maybe some very light background color tint to better differentiate sections?)

**Comment by willow446** [comment]
Implemented some styling for the markdown styling in b5277bcfd8645a9b61a63ecf509bae6bd6738c5b

Let me know what you think. We can still add a tint surrounding each subsection if you find it's challenging to differentiate sections after the spacing change I just pushed.

**Comment by jnny** [comment]
Looks good! And I like that idea - can we try it out?

**Comment by willow446** [comment]
Sure! will push a version with tint in a few.

**Comment by willow446** [comment]
f69496c443cc81034ab0d3b1ba2acb46183d336c

**Comment by jnny** [comment]
I added more padding above the gradient footer in a recent commit.

Let's improve the single-page layout with eg hero banner for page titles, narrower margins, etc and make sure it renders nicely on mobile, laptop, and large screens.

**Comment by willow446** [comment]
Any suggestions for specifics here? The site has changed a lot since this ticket was first opened.

**Comment by jnny** [comment]
Two ideas:
- [ ] hero banner for page titles (like the homepage)
- [ ] narrower default margins

**Comment by willow446** [comment]
@jnny to add to that list, maybe centered figures? I'm personally not a fan of left-aligned images.

Can also set it up so figures can have optional captions.

**Comment by jnny** [comment]
Yeah good call, i think i manually centered all the figures in the faq..

**Comment by willow446** [comment]
better margins and centered photos (also on mobile) were added earlier today.

Just added optional hero styling on markdown-only pages. for example: https://ouisync.net/security/
There's also an optional subtitle that would go right below the rendered title, also in front of the purple bg.

This should close this issue, but feel free to reopen if I'm missing something.
