### ISSUE TITLE
Create Download page

### ISSUE THREAD

**Issue by jnny** [equalitie/ouisync-web#15]
Inspiration: https://www.torproject.org/download/

For:
- Android
- Windows
- Linux
- iOS (Coming Soon! label)
- Direct downloads (hosting APKs on Github for various builds)

Need:
- Icons
- Install packages/links
- Signatures and verification instructions (see https://censorship.no/download, https://support.torproject.org/tbb/how-to-verify-signature/ for examples)

**Comment by willow446** [comment]
Added the scaffolding for the download page in: df1504248769720e5afa1a0fb6c01e127e02d780

**Comment by jnny** [comment]
Waiting on published releases from the Ouisync devs

**Comment by willow446** [comment]
This is all up to the latest spec as of now.
