### ISSUE TITLE
Style About page

### ISSUE THREAD

**Issue by jnny** [equalitie/ouisync-web#22]
Could use help with:
- [x] Flow of Team Member photos
- [ ] Header and margins (this would be default single page layout design)

**Comment by jnny** [comment]
I think we can close this after documenting the process for adding new pages @willow446

**Comment by willow446** [comment]
did some work to make adding new pages more straightforward, I'll make sure to document everything then we can close this.

**Comment by willow446** [comment]
Documentation for adding and editing pages was added today to the CONTRIBUTING.md file.
