### ISSUE TITLE
Configure Weblate components

### ISSUE THREAD

**Issue by jnny** [equalitie/ouisync-web#27]
I'll update this ticket with process and progress :)

https://hosted.weblate.org/projects/ouisync/

**Comment by jnny** [comment]
@willow446 curious why you chose to use "en-us" and then "fr" language codes.. can we make it all standard 2 letter codes?

**Comment by jnny** [comment]
I would do a find and replace myself, but not sure if this will mess up something in Hugo's process..
https://github.com/search?q=repo%3Awillow446%2Fwillow446.github.io+en-us&type=code

**Comment by willow446** [comment]
I just defaulted to en-us without thinking because that was the main language code I've used  :sweat_smile:, I switched to using `en` in a06637b3eaf47533f1759822081529668928eac1

**Comment by jnny** [comment]
Once we move the site over to eQ's github we can set up version control, but for now I was able to successfully upload the i18n/en.json file for translation in Weblate and we can at least start localizing :) - https://hosted.weblate.org/projects/ouisync/website/

Are there other pages whose content is not captured in the json file @willow446 ?

**Comment by jnny** [comment]
> But for now, everything is in the `en.json` file.

Truly everything? cuz that's amazing :)

**Comment by willow446** [comment]
So I have the main content pages translated into string form, but the Security and Privacy pages are not translated in this way. 
For those pages there are two options:
- cut them up into individual strings, add these strings to en.json 
- wait for weblate to roll out the full markdown translation system

**Comment by jnny** [comment]
Closing as all components have been configured, by and large. we can make a new issue when we change from Hugo to eQ-web.
