### ISSUE TITLE
add aria labels

### ISSUE THREAD

**Issue by willow446** [equalitie/ouisync-web#34]

**Comment by willow446** [comment]
The main benefactor of aria-labels, the nav bar, has been added in 78a66a0..c4f7b4a

**Comment by jnny** [comment]
Just shared with @willow446 in a DM, but adding to this ticket a useful tool for website a11y checks: https://sa11y.netlify.app/overview/

**Comment by jnny** [comment]
I think I took care of most all of these in some recent commits, so closing for now :)
