### ISSUE TITLE
Add Link Preview Images

### ISSUE THREAD

**Issue by willow446** [equalitie/ouisync-web#37]
We should be able to reuse the social media ouisync headers we made earlier.

Each long-standing subpage should have a preview that fits the page info, eg FAQ should say "frequently asked questions" etc.

**Comment by jnny** [comment]
What's the process to implement this?

**Comment by jnny** [comment]
Relatedly, we should change faq.md / .html to support (more translateable and flexible for future content)

**Comment by willow446** [comment]
> What's the process to implement this?

setting the right meta and open graph tags in the html <head> element. More info here: https://andrejgajdos.com/how-to-create-a-link-preview/

With hugo we'll basically have a switch statement that inserts different metadata depending on the page name.

**Comment by willow446** [comment]
done in 25b4eaf8b603f06e68e03d1268fc15c77036aca9
