### ISSUE TITLE
Make sure there is alt-text on all images

### ISSUE THREAD

**Issue by willow446** [equalitie/ouisync-web#39]

**Comment by jnny** [comment]
I added alt text to homepage images in a recent commit. Will look at the other pages tomorrow unless you beat me to it!

**Comment by willow446** [comment]
woot, thank you @jnny

**Comment by jnny** [comment]
I think I get em all in this latest commit @willow446 - https://github.com/equalitie/ouisync-web/commit/1a24642e99b67cfd98eb15e610909f159a1cfa00
