### ISSUE TITLE
Team's photos need to be redirected to the eq website 

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-web#44]
At the moment, clicking on a photo of a team member leads to theeir github repos - whereas the text says that full bios are availabel on eQ website;  Then - when clickign on photos, what should open is eQ website (andnot github repos as now)

**Comment by jnny** [comment]
Fixed in https://github.com/equalitie/ouisync-web/commit/164edfea0d181938859ee700dabf369b59bc8f0d.
