### ISSUE TITLE
some Ouisync weblate links are directed to incorrect page

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-web#45]
![Screenshot 2023-08-04 at 15 02 26](https://github.com/equalitie/ouisync-web/assets/121942562/0b25f0ec-630f-4cbc-9bf4-70aaa52930ad)
The ouisync project link is directed to the wrong address and gives the page not found 404 error.
https://hosted.weblate.org/ouisync it misses the word projects after the weblate.org/projects/ouisync is the correct one
this can be seen here https://hosted.weblate.org/projects/ouisync/ - which opens the project page.

**Comment by jnny** [comment]
Good catch, fixed!
