### ISSUE TITLE
Community page idiosyncracies...

### ISSUE THREAD

**Issue by jnny** [equalitie/ouisync-web#47]
![image](https://github.com/equalitie/ouisync-web/assets/1790886/32f9d3f7-2044-46bf-aacb-ba3880909687)

Two formatting issues - 1) can you look into the spacing differential between the first and second sections (between the links and the paragraph preceding it) @willow446 ?

I will look into 2) enlarging the 'Translated' SVG

**Comment by willow446** [comment]
![image](https://github.com/equalitie/ouisync-web/assets/29606582/0fa4b563-e6bb-44fc-8f75-1dfbce4187e8)

In english the sections all line up which looks nicer imo (thanks for enlarging the translate badge!) 
In other languages the font height differs so things wont always lineup exactly, lmk if there's any other ideas you're interested in before closing this.

**Comment by jnny** [comment]
Looks good to me! Closing :)
