### ISSUE TITLE
Privacy policy needs to be on the website...

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-web#49]
The ouisync privacy policy has been defined, but seems it hasn't been added to the website, only to the app itself.  

Please can you add it to the About page?

**Comment by jnny** [comment]
Hi @IvanaBlzvc and sorry for only just seeing this!
The Privacy policy is linked to in the footer across the site - do you have a better idea of how to present it?

**Comment by willow446** [comment]
As of `31a5b18` there is a link to the privacy page in the footer that updates depending on language settings. Lmk if there's any more work here needed to close this topic.
