### ISSUE TITLE
Add redirect from ouisync.net/download

### ISSUE THREAD

**Issue by jnny** [equalitie/ouisync-web#72]
Tiny one but probably will take you two minutes, @willow446 :)

I would like to be able to say "go to ouisync.net/download" to download the app quickly, but the real url is ouisync.net/#download. is this something we can configure in the yaml front matter?

**Comment by jnny** [comment]
Closed in https://github.com/equalitie/ouisync-web/pull/73

**Comment by willow446** [comment]
I think this just needs a separate hugo content page that has an html redirect in it. 
Going to try something real quick and see if it works with hugo/github pages.

**Comment by willow446** [comment]
After getting around more [weird hugo issues](https://github.com/gohugoio/hugo/issues/7296) this functionality is implemented in a68c735
