### ISSUE TITLE
Create a css img class to automate screenshot drop shadows

### ISSUE THREAD

**Issue by jnny** [equalitie/ouisync-web#76]
iirc, for the original Ouisync FAQ, I manually ran each screenshot through inkscape to increase canvas size and add that nice little drop shadow: 

![image](https://github.com/equalitie/ouisync-web/assets/1790886/58c629e4-bca5-42e5-a895-390ea87085b4)

i know we could just do this automatically with some css magic.. thoughts?

this is decidedly a "nice to have" - nonessential but would look fresh and save us documentarians time :)

**Comment by jnny** [comment]
cc @IvanaBlzvc :)

**Comment by jnny** [comment]
or maybe this is something already addressed in Fastlane's Screengrab functionality?? @willow446

**Comment by willow446** [comment]
I think it would be best to take the "raw" screenshots (i.e. with no shadows) and then style them on the site, then apply CSS to the locations on the site where we want this effect. Here's what the CSS to add this would look like (we can tweak the actual shadow effect to our preference):

```css
details figure image { 
    box-shadow: 0 .5em 1em -.125em rgba(10,10,10,.1),0 0 0 1px rgba(10,10,10,.02);
}
```

Happy to add this css effect when we get the shadow-less version of all the images added in.

**Comment by jnny** [comment]
> I think it would be best to take the "raw" screenshots (i.e. with no shadows) and then style them on the site, then apply CSS to the locations on the site where we want this effect. Here's what the CSS to add this would look like (we can tweak the actual shadow effect to our preference):
> 
> ```css
> details figure image { 
>     box-shadow: 0 .5em 1em -.125em rgba(10,10,10,.1),0 0 0 1px rgba(10,10,10,.02);
> }
> ```
> 
> Happy to add this css effect when we get the shadow-less version of all the images added in.

Awesome! Yes, I have the originals somewhere - but given there will be an extensive update of the FAQ soon, I'll confer with @IvanaBlzvc on this - she will be happy there is a simple solution! <3
